FROM python:3.7

RUN pip install --upgrade pip
RUN pip install numpy Pillow scipy pandas time
RUN pip install pyopenvdb

##################################
# ENVIRONMENT
##################################
ENV LD_LIBRARY_PATH /usr/local/lib/python3.7/site-packages

