name: 3D IISPH Makefile CI (V3)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build
      run: cd simulation/v3\ -\ IISPH\ 3D && make
